### ISSUE TITLE
Error while running fetch "xt_connmark.h: no such file or directory"

### ISSUE THREAD

**Issue by navinkumarr** [threema-ch/webrtc-build-docker#40] opened 2023-11-03 10:55 UTC
While running the `./cli.sh fetch` command, I am getting following error. Any idea what could be wrong here.

```
[1:55:50] Still working on:
[1:55:50]   src/third_party/icu
Syncing projects: 100% (237/237), done.

________ running 'cipd ensure -log-level error -root /webrtc -ensure-file /tmp/tmpw4umsw_w.ensure' in '.'
[P2031 12:00:21.151 client.go:1913 E] [unzip 168/190] Failed to install chromium/third_party/android_toolchain/android_toolchain in "src/third_party/android_toolchain/ndk": adding files to the site root: lstat /webrtc/.cipd/pkgs/188/NSOM616pOQCfRfDAhC72ltgjyUQp9lAWCMzlmgB18dAC/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/linux/netfilter/xt_connmark.h: no such file or directory
Errors:
  failed to install chromium/third_party/android_toolchain/android_toolchain in "src/third_party/android_toolchain/ndk": adding files to the site root: lstat /webrtc/.cipd/pkgs/188/NSOM616pOQCfRfDAhC72ltgjyUQp9lAWCMzlmgB18dAC/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/linux/netfilter/xt_connmark.h: no such file or directory
Error: Command 'cipd ensure -log-level error -root /webrtc -ensure-file /tmp/tmpw4umsw_w.ensure' returned non-zero exit status 1
[P2031 12:00:21.151 client.go:1913 E] [unzip 168/190] Failed to install chromium/third_party/android_toolchain/android_toolchain in "src/third_party/android_toolchain/ndk": adding files to the site root: lstat /webrtc/.cipd/pkgs/188/NSOM616pOQCfRfDAhC72ltgjyUQp9lAWCMzlmgB18dAC/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/linux/netfilter/xt_connmark.h: no such file or directory
Errors:
  failed to install chromium/third_party/android_toolchain/android_toolchain in "src/third_party/android_toolchain/ndk": adding files to the site root: lstat /webrtc/.cipd/pkgs/188/NSOM616pOQCfRfDAhC72ltgjyUQp9lAWCMzlmgB18dAC/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/linux/netfilter/xt_connmark.h: no such file or directory
```

**Comment by zerephe** [comment] 2023-11-08 09:27
Found this information about this. But still can't figure out the solution.
https://www.cnblogs.com/YYFaGe/p/16804359.html
https://blog.51cto.com/u_847102/5270092

**Comment by threema-danilo** [comment] 2023-11-08 17:38
I cannot reproduce this issue. Probably something related to your local setup?

Closing this, since (note from README):

> NOTE: We do not provide any support related to building special versions, or related to issues with your Docker installation, or with regard to bugs in the WebRTC codebase itself. We also do not provide any support on how to integrate the resulting build into your application.

Feel free to leave a comment, as help for others, if you find a solution, but we can't help here.

**Closed by threema-danilo** 2023-11-08 17:38 UTC

**Comment by zerephe** [comment] 2023-11-08 19:43
Basically mac os file system is case-sensitive by defalut. That means filename.file and FILENAME.file are considered as the same files and mac os removes one of them.
Solutions:
1) Erase your mac storage and reformat the file system with disabled case-sensitive
2) Fetch webrtc directly in the docker environment

**Comment by threema-danilo** [comment] 2023-11-09 07:39
If that's the cause of the issue, then this would affect all consumers of WebRTC. You could try to look for a matching issue at https://bugs.webrtc.org/, or create a new report if you can't find one.

**Comment by fippo** [comment] 2023-11-19 07:05
This has already been addressed upstream a few months back: https://bugs.chromium.org/p/chromium/issues/detail?id=1457386
